-- ******************************** SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Snowflake Demo 35, v11 vs v10 by eric.ruiz+yew@sqldbm.com *

ALTER TABLE dim_TABLE_41
    DROP COLUMN to_dts;

ALTER TABLE dim_TABLE_41
    DROP COLUMN load_dts;

CREATE TABLE TABLE_43
(
 to_dts   timestamp_ntz(9) NOT NULL,
 load_dts timestamp_ntz(9) NOT NULL
);

CREATE VIEW VIEW_2

  Comment = 'No Comment Provided'

AS
(
  

);