-- ******************************* SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: Snowflake Demo 76, v9 vs v8 by eric.ruiz+yew@sqldbm.com *

ALTER TABLE SUPPLYCHAIN.WAREHOUSEZONEDIM_T
    ADD COLUMN column1 int NOT NULL;