-- ************************** SqlDBM: Snowflake *************************
-- **** Generated by SqlDBM: Snowflake 43 by eric.ruiz+yew@sqldbm.com ***

-- **************************************  SUPPLYCHAIN.PII
CREATE TAG SUPPLYCHAIN.PII ALLOWED_VALUES 'NO', 'YES';
