-- ************************** SqlDBM: Snowflake *************************
-- **** Generated by SqlDBM: Snowflake 43 by eric.ruiz+yew@sqldbm.com ***

-- **************************************  SUPPLYCHAIN.RETENTION_PERIOD
CREATE TAG SUPPLYCHAIN.RETENTION_PERIOD ALLOWED_VALUES '7 YEARS';
