-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 76 by eric.ruiz+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.DATA_OWNER
CREATE TAG SUPPLYCHAIN.DATA_OWNER ALLOWED_VALUES 'SUPPLYCHAINTEAM';
