-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.ACCESS_LEVEL
CREATE TAG SUPPLYCHAIN.ACCESS_LEVEL ALLOWED_VALUES 'RESTRICTED';
