-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CALCULATE_TOTAL_MAINTENANCE_COST
CREATE FUNCTION ACMECORP.SUPPLYCHAIN.CALCULATE_TOTAL_MAINTENANCE_COST("WAREHOUSE_ID" NUMBER(38,0))
RETURNS NUMBER(10,2)
LANGUAGE SQL
AS '
  (
    SELECT COALESCE(SUM(MaintenanceCost), 0)
    FROM WarehouseMaintenanceFact
    WHERE WarehouseKey = warehouse_id
  )
';
