-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** "42_T"
CREATE TABLE "42_T"
(
 LastUpdated timestamp NOT NULL
);
