-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** "43_T"
CREATE TABLE "43_T"
(
 ADDRESS string NOT NULL
);
