-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** "45_T"
CREATE TABLE "45_T"
(
 ADDRESS string NOT NULL
);
