-- ************************** SqlDBM: Snowflake *************************
-- **** Generated by SqlDBM: Snowflake 43 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** Customer1
CREATE TABLE Customer1
(
 cusid   integer NOT NULL,
 fname   string NOT NULL,
 ORDERID number(38,0) NOT NULL COMMENT 'The ''OrderID'' column contains data related to ''orderid''. This column likely represents an identifier.',

 CONSTRAINT PK_1 PRIMARY KEY ( cusid ),
 CONSTRAINT FK_1 FOREIGN KEY ( ORDERID ) REFERENCES SUPPLYCHAIN.ORDERS ( ORDERID )
) WITH TAG (SUPPLYCHAIN.PII = '');
