-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** dim_TABLE_41_T
CREATE TABLE dim_TABLE_41_T
(
 from_dts    timestamp_ntz(9) NOT NULL,
 to_dts      timestamp_ntz(9) NOT NULL,
 load_dts    timestamp_ntz(9) NOT NULL,
 LastUpdated timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( from_dts )
);
