-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** dim_TABLE_41_T
CREATE TABLE dim_TABLE_41_T
(
 from_dts timestamp_ntz(9) NOT NULL,
 to_dts   timestamp_ntz(9) NOT NULL,
 ADDRESS  string NOT NULL,
 load_dts timestamp_ntz(9) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( from_dts )
);
