-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_fraud_incident
CREATE TABLE finance_analytics.fact_fraud_incident
(
 fraud_key       int NOT NULL COMMENT 'Unique identifier for each fraud incident record' CONSTRAINT pk_fact_fraud PRIMARY KEY,
 time_key        int NOT NULL COMMENT 'Foreign key linking to the time dimension for fraud incident timing' CONSTRAINT fk_fraud_time REFERENCES finance_analytics.dim_time,
 customer_key    int COMMENT 'Foreign key linking to the customer dimension for fraud-related customer information' CONSTRAINT fk_fraud_customer REFERENCES finance_analytics.dim_customer,
 account_key     int COMMENT 'Foreign key linking to the account dimension for fraud-related account details' CONSTRAINT fk_fraud_account REFERENCES finance_analytics.dim_account,
 card_key        int COMMENT 'Foreign key linking to the card dimension for fraud-related card information' CONSTRAINT fk_fraud_card REFERENCES finance_analytics.dim_card,
 transaction_key int COMMENT 'Foreign key linking to the transaction dimension for the specific fraudulent transaction' CONSTRAINT fk_fraud_txn REFERENCES finance_analytics.fact_transaction,
 channel_key     int COMMENT 'Foreign key linking to the channel dimension for the fraud incident channel' CONSTRAINT fk_fraud_channel REFERENCES finance_analytics.dim_channel,
 device_key      int COMMENT 'Foreign key linking to the device dimension for the device associated with the fraud' CONSTRAINT fk_fraud_device REFERENCES finance_analytics.dim_device,
 loss_amount     decimal(15, 2) NOT NULL COMMENT 'Total monetary loss amount resulting from the fraud incident',
 recovery_amount decimal(15, 2) COMMENT 'Amount recovered from the fraud incident',
 fraud_type      string NOT NULL COMMENT 'Account Takeover, Card Present, Card Not Present, Phishing',
 status          string NOT NULL COMMENT 'Open, Investigating, Recovered, Write-off'
)
 COMMENT 'Confirmed or suspected fraud cases with loss and recovery';
