-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_loan_performance
CREATE TABLE finance_analytics.fact_loan_performance
(
 loan_perf_key       int NOT NULL COMMENT 'Unique identifier for loan performance records' CONSTRAINT pk_fact_loan_performance PRIMARY KEY,
 account_key         int NOT NULL COMMENT 'Foreign key referencing the specific loan account' CONSTRAINT fk_loan_account REFERENCES finance_analytics.dim_account,
 customer_key        int NOT NULL COMMENT 'Foreign key referencing the customer associated with the loan' CONSTRAINT fk_loan_customer REFERENCES finance_analytics.dim_customer,
 product_key         int NOT NULL COMMENT 'Foreign key referencing the loan product type' CONSTRAINT fk_loan_product REFERENCES finance_analytics.dim_product,
 time_key            int NOT NULL COMMENT 'Foreign key referencing the time dimension for performance snapshot' CONSTRAINT fk_loan_time REFERENCES finance_analytics.dim_time,
 principal_amount    decimal(15, 2) NOT NULL COMMENT 'Original loan principal amount',
 outstanding_balance decimal(15, 2) NOT NULL COMMENT 'Current remaining balance on the loan',
 payment_amount      decimal(15, 2) COMMENT 'Amount of payment made in the current period',
 days_past_due       int COMMENT 'Number of days the loan payment is overdue',
 loan_status         string NOT NULL COMMENT 'Performing, Delinquent, Default'
)
 COMMENT 'Fact table tracking performance and health of loan accounts';
