-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_device
CREATE TABLE finance_analytics.dim_device
(
 device_key  int NOT NULL COMMENT 'Unique surrogate key for each device record' CONSTRAINT pk_dim_device PRIMARY KEY,
 device_id   string COMMENT 'Unique identifier for the specific device',
 device_type string COMMENT 'Mobile, Desktop, Tablet, ATM, POS',
 os_nm       string COMMENT 'Name of the operating system running on the device',
 os_version  string COMMENT 'Version of the operating system on the device'
)
 COMMENT 'Device metadata for digital transactions/interactions';
