-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_card
CREATE TABLE finance_analytics.dim_card
(
 card_key     int NOT NULL COMMENT 'Unique surrogate key for each payment card record' CONSTRAINT pk_dim_card PRIMARY KEY,
 card_id      string NOT NULL COMMENT 'Unique identifier for the physical or virtual card',
 card_brand   string COMMENT 'Visa, MasterCard, Amex',
 card_type    string COMMENT 'Debit, Credit, Prepaid',
 product_key  int COMMENT 'Foreign key linking to the associated product details',
 customer_key int COMMENT 'Foreign key linking to the associated customer record',
 open_dt      date COMMENT 'Date when the card was first activated or issued',
 close_dt     date COMMENT 'Date when the card was closed or deactivated'
)
 COMMENT 'Payment card instruments linked to customers and products';
