-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_account_balance
CREATE TABLE finance_analytics.fact_account_balance
(
 balance_key       int NOT NULL COMMENT 'Unique key for each balance record' CONSTRAINT pk_fact_account_balance PRIMARY KEY,
 account_key       int NOT NULL COMMENT 'Foreign key linking to the account dimension' CONSTRAINT fk_bal_account REFERENCES finance_analytics.dim_account,
 customer_key      int NOT NULL COMMENT 'Foreign key linking to the customer dimension' CONSTRAINT fk_bal_customer REFERENCES finance_analytics.dim_customer,
 time_key          int NOT NULL COMMENT 'Foreign key linking to the time dimension' CONSTRAINT fk_bal_time REFERENCES finance_analytics.dim_time,
 current_balance   decimal(15, 2) NOT NULL COMMENT 'Total current balance of the account',
 available_balance decimal(15, 2) COMMENT 'Balance available for transactions or withdrawals',
 avg_daily_balance decimal(15, 2) COMMENT 'Average daily balance for the period'
)
 COMMENT 'Periodic balance snapshot for each account and customer over time';
