-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_card_authorization
CREATE TABLE finance_analytics.fact_card_authorization
(
 auth_key      int NOT NULL COMMENT 'Unique identifier for each card authorization transaction' CONSTRAINT pk_fact_card_auth PRIMARY KEY,
 time_key      int NOT NULL COMMENT 'Foreign key referencing the time dimension for transaction timestamp' CONSTRAINT fk_auth_time REFERENCES finance_analytics.dim_time,
 customer_key  int NOT NULL COMMENT 'Foreign key referencing the customer involved in the transaction' CONSTRAINT fk_auth_customer REFERENCES finance_analytics.dim_customer,
 account_key   int NOT NULL COMMENT 'Foreign key referencing the account associated with the authorization' CONSTRAINT fk_auth_account REFERENCES finance_analytics.dim_account,
 card_key      int COMMENT 'Foreign key referencing the specific card used in the transaction' CONSTRAINT fk_auth_card REFERENCES finance_analytics.dim_card,
 merchant_key  int COMMENT 'Foreign key referencing the merchant where the transaction occurred' CONSTRAINT fk_auth_merchant REFERENCES finance_analytics.dim_merchant,
 channel_key   int COMMENT 'Foreign key referencing the transaction channel (e.g., online, in-store)' CONSTRAINT fk_auth_channel REFERENCES finance_analytics.dim_channel,
 device_key    int COMMENT 'Foreign key referencing the device used for the transaction' CONSTRAINT fk_auth_device REFERENCES finance_analytics.dim_device,
 currency_key  int COMMENT 'Foreign key referencing the currency of the transaction' CONSTRAINT fk_auth_currency REFERENCES finance_analytics.dim_currency,
 auth_amount   decimal(15, 2) NOT NULL COMMENT 'Total authorized transaction amount',
 auth_status   string NOT NULL COMMENT 'Approved, Declined, Reversed',
 response_code string COMMENT 'Response code from the payment authorization system'
)
 COMMENT 'Pre-settlement card authorizations for spend analytics and decline reasons';
