-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_customer
CREATE TABLE finance_analytics.dim_customer
(
 customer_key  int NOT NULL COMMENT 'Unique surrogate key for each customer in the dimension' CONSTRAINT pk_dim_customer PRIMARY KEY,
 customer_id   string NOT NULL COMMENT 'External/natural customer identifier',
 first_nm      string NOT NULL COMMENT 'Customer''s first name',
 last_nm       string NOT NULL COMMENT 'Customer''s last name',
 email         string COMMENT 'Customer''s email address',
 phone_number  string COMMENT 'Customer''s primary contact phone number',
 birth_dt      date COMMENT 'Customer''s date of birth',
 age_group     string COMMENT 'Categorized age group of the customer',
 income_level  string COMMENT 'Customer''s income category',
 is_active     boolean NOT NULL COMMENT 'Flag indicating if the customer is active',
 effective_dt  date NOT NULL COMMENT 'Date from which the customer record is valid',
 expiration_dt date NOT NULL COMMENT 'Date until which the customer record remains valid'
)
 COMMENT 'Dimension containing customer master data';
