-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_region
CREATE TABLE finance_analytics.dim_region
(
 region_key int NOT NULL COMMENT 'Unique identifier for each geographic region' CONSTRAINT pk_dim_region PRIMARY KEY,
 country    string NOT NULL COMMENT 'Country associated with the geographic region',
 region_nm  string COMMENT 'Descriptive name of the geographic region',
 state      string COMMENT 'State or province within the geographic region',
 city       string COMMENT 'City within the geographic region'
)
 COMMENT 'Geographic region reference for branches, customers, and merchants';
