-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_time
CREATE TABLE finance_analytics.dim_time
(
 time_key     int NOT NULL COMMENT 'Unique identifier for each time record in the dimension' CONSTRAINT pk_dim_time PRIMARY KEY,
 full_dt      date NOT NULL COMMENT 'Complete calendar date representing the time record',
 year_num     int NOT NULL COMMENT 'Numeric representation of the year',
 quarter_num  int NOT NULL COMMENT 'Quarter of the year (1-4)',
 month_num    int NOT NULL COMMENT 'Numeric representation of the month (1-12)',
 month_nm     string NOT NULL COMMENT 'Full name of the month',
 day_of_month int NOT NULL COMMENT 'Day of the month (1-31)',
 day_of_week  int NOT NULL COMMENT 'Numeric representation of the day of week (1-7)',
 day_nm       string NOT NULL COMMENT 'Full name of the day',
 is_weekend   boolean NOT NULL COMMENT 'Boolean flag indicating if the date is a weekend'
)
 COMMENT 'Standard time dimension for analytics and trend reporting';
