-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_account
CREATE TABLE finance_analytics.dim_account
(
 account_key           int NOT NULL COMMENT 'Unique surrogate key for each account in the dimension' CONSTRAINT pk_dim_account PRIMARY KEY,
 account_id            string NOT NULL COMMENT 'Unique identifier for the account in the source system',
 customer_key          int NOT NULL COMMENT 'Foreign key linking to the customer dimension',
 account_type          string NOT NULL COMMENT 'Checking, Savings, Credit, Loan, etc.',
 account_status        string NOT NULL COMMENT 'Valid Values are: Active, Closed, Suspended',
 opening_dt            date NOT NULL COMMENT 'Date when the account was initially opened',
 closing_dt            date COMMENT 'Date when the account was closed (if applicable)',
 branch_key            int NOT NULL COMMENT 'Foreign key linking to the branch dimension',
 account_balance_limit decimal(15, 2) COMMENT 'Maximum balance or credit limit for the account',
 effective_dt          date NOT NULL COMMENT 'Date from which the account details are valid',
 expiration_dt         date NOT NULL COMMENT 'Date until which the account details remain valid'
)
 COMMENT 'Dimension containing account master and relationship information';
