-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_channel
CREATE TABLE finance_analytics.dim_channel
(
 channel_key  int NOT NULL COMMENT 'Unique identifier for each channel in the dimension table' CONSTRAINT pk_dim_channel PRIMARY KEY,
 channel_code string NOT NULL COMMENT 'POS, ATM, WEB, MOBILE, IVR, BRANCH',
 channel_nm   string NOT NULL COMMENT 'Descriptive name of the transaction channel'
)
 COMMENT 'Channel used for transactions and interactions';
