-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_merchant
CREATE TABLE finance_analytics.dim_merchant
(
 merchant_key int NOT NULL COMMENT 'Unique surrogate key for merchant dimension' CONSTRAINT pk_dim_merchant PRIMARY KEY,
 merchant_id  string NOT NULL COMMENT 'Unique identifier of the merchant in the source system',
 merchant_nm  string NOT NULL COMMENT 'Full name of the merchant or business',
 mcc_code     string COMMENT 'Merchant Category Code',
 region_key   int COMMENT 'Foreign key linking to the region dimension' CONSTRAINT fk_merchant_region REFERENCES finance_analytics.dim_region
)
 COMMENT 'Merchant directory for card transactions';
