-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_product
CREATE TABLE finance_analytics.dim_product
(
 product_key      int NOT NULL COMMENT 'Unique surrogate key for each financial product' CONSTRAINT pk_dim_product PRIMARY KEY,
 product_id       string NOT NULL COMMENT 'External identifier for the product',
 product_nm       string NOT NULL COMMENT 'Descriptive name of the financial product',
 product_category string NOT NULL COMMENT 'Deposit, Loan, Credit Card, etc.',
 product_type     string COMMENT 'Subtype of product',
 interest_rate    decimal(5, 2) COMMENT 'Applicable interest rate for the product',
 min_balance      decimal(15, 2) COMMENT 'Minimum balance required for the product',
 effective_dt     date NOT NULL COMMENT 'Date from which the product details are valid',
 expiration_dt    date NOT NULL COMMENT 'Date until which the product details remain valid'
)
 COMMENT 'Dimension describing financial products offered to customers';
