-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_customer_interaction
CREATE TABLE finance_analytics.fact_customer_interaction
(
 interaction_key     int NOT NULL COMMENT 'Unique primary key for customer interaction records' CONSTRAINT pk_fact_interaction PRIMARY KEY,
 time_key            int NOT NULL COMMENT 'Foreign key linking to the time dimension for interaction timestamp' CONSTRAINT fk_int_time REFERENCES finance_analytics.dim_time,
 customer_key        int NOT NULL COMMENT 'Foreign key linking to the customer dimension for customer identification' CONSTRAINT fk_int_customer REFERENCES finance_analytics.dim_customer,
 channel_key         int NOT NULL COMMENT 'Foreign key linking to the channel dimension for interaction channel details' CONSTRAINT fk_int_channel REFERENCES finance_analytics.dim_channel,
 device_key          int COMMENT 'Foreign key linking to the device dimension for interaction device information' CONSTRAINT fk_int_device REFERENCES finance_analytics.dim_device,
 interaction_type    string NOT NULL COMMENT 'Call, Chat, Email, Branch Visit',
 interaction_minutes int COMMENT 'Total duration of the customer interaction in minutes',
 satisfaction_score  decimal(4, 2) COMMENT 'Customer satisfaction rating for the interaction on a scale of 0-10',
 resolved_flag       boolean NOT NULL COMMENT 'Boolean indicator of whether the customer interaction was successfully resolved'
)
 COMMENT 'Customer service interactions for CX analytics and resolution tracking';
