-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_transaction
CREATE TABLE finance_analytics.fact_transaction
(
 transaction_key    int NOT NULL COMMENT 'Unique identifier for each financial transaction in the system' CONSTRAINT pk_fact_transaction PRIMARY KEY,
 account_key        int NOT NULL COMMENT 'Foreign key linking to the specific account involved in the transaction' CONSTRAINT fk_trans_account REFERENCES finance_analytics.dim_account,
 customer_key       int NOT NULL COMMENT 'Foreign key identifying the customer associated with the transaction' CONSTRAINT fk_trans_customer REFERENCES finance_analytics.dim_customer,
 product_key        int NOT NULL COMMENT 'Foreign key referencing the financial product related to the transaction' CONSTRAINT fk_trans_product REFERENCES finance_analytics.dim_product,
 branch_key         int NOT NULL COMMENT 'Foreign key indicating the branch where the transaction was processed' CONSTRAINT fk_trans_branch REFERENCES finance_analytics.dim_branch,
 time_key           int NOT NULL COMMENT 'Foreign key representing the timestamp of the transaction' CONSTRAINT fk_trans_time REFERENCES finance_analytics.dim_time,
 transaction_amount decimal(15, 2) NOT NULL COMMENT 'Total monetary value of the financial transaction',
 transaction_type   string NOT NULL COMMENT 'Deposit, Withdrawal, Payment, Transfer, etc.',
 transaction_status string NOT NULL COMMENT 'Completed, Pending, Failed',
 transaction_fee    decimal(10, 2) COMMENT 'Additional charges or fees associated with the transaction'
)
 COMMENT 'Fact table capturing all monetary customer transactions';
