-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_branch
CREATE TABLE finance_analytics.dim_branch
(
 branch_key int NOT NULL COMMENT 'Unique surrogate key for each bank branch in the dimension table' CONSTRAINT pk_dim_branch PRIMARY KEY,
 branch_id  string NOT NULL COMMENT 'External unique identifier for the bank branch',
 branch_nm  string NOT NULL COMMENT 'Full name or designation of the bank branch',
 region     string COMMENT 'Geographic region where the branch is located',
 address    string COMMENT 'Full street address of the branch location',
 city       string COMMENT 'City where the branch is situated',
 state      string COMMENT 'State or province of the branch location',
 country    string COMMENT 'Country where the branch is located',
 opening_dt date COMMENT 'Date when the branch was first established or opened',
 is_active  boolean NOT NULL COMMENT 'Boolean flag indicating whether the branch is currently operational'
)
 COMMENT 'Dimension containing information about bank branches and locations';
