-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_chargeback_dispute
CREATE TABLE finance_analytics.fact_chargeback_dispute
(
 dispute_key     int NOT NULL COMMENT 'Unique identifier for each chargeback dispute record' CONSTRAINT pk_fact_dispute PRIMARY KEY,
 time_key        int NOT NULL COMMENT 'Foreign key linking to the time dimension for dispute timestamp' CONSTRAINT fk_dispute_time REFERENCES finance_analytics.dim_time,
 customer_key    int NOT NULL COMMENT 'Foreign key linking to the customer dimension for the disputing customer' CONSTRAINT fk_dispute_customer REFERENCES finance_analytics.dim_customer,
 account_key     int NOT NULL COMMENT 'Foreign key linking to the account dimension related to the dispute' CONSTRAINT fk_dispute_account REFERENCES finance_analytics.dim_account,
 card_key        int COMMENT 'Foreign key linking to the card dimension (nullable)' CONSTRAINT fk_dispute_card REFERENCES finance_analytics.dim_card,
 merchant_key    int COMMENT 'Foreign key linking to the merchant dimension (nullable)' CONSTRAINT fk_dispute_merchant REFERENCES finance_analytics.dim_merchant,
 transaction_key int COMMENT 'Foreign key linking to the original transaction dimension (nullable)' CONSTRAINT fk_dispute_txn REFERENCES finance_analytics.fact_transaction,
 dispute_reason  string NOT NULL COMMENT 'Reason for initiating the chargeback dispute',
 dispute_amount  decimal(15, 2) NOT NULL COMMENT 'Total monetary amount of the chargeback dispute',
 dispute_status  string NOT NULL COMMENT 'Open, Under Review, Resolved, Rejected'
)
 COMMENT 'Card and deposit disputes/chargebacks linked to original transactions';
