-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_currency
CREATE TABLE finance_analytics.dim_currency
(
 currency_key  int NOT NULL COMMENT 'Unique identifier for each currency in the dimension table' CONSTRAINT pk_dim_currency PRIMARY KEY,
 currency_code string NOT NULL COMMENT 'ISO 4217 code, e.g., USD',
 currency_nm   string NOT NULL COMMENT 'Full name of the currency',
 symbol        string COMMENT 'Currency symbol representing the monetary unit'
)
 COMMENT 'Supported currencies for accounts and transactions';
