-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.fact_fee_assessed
CREATE TABLE finance_analytics.fact_fee_assessed
(
 fee_key      int NOT NULL COMMENT 'Unique identifier for each fee record' CONSTRAINT pk_fact_fee PRIMARY KEY,
 time_key     int NOT NULL COMMENT 'Foreign key referencing the time dimension for the fee assessment' CONSTRAINT fk_fee_time REFERENCES finance_analytics.dim_time,
 account_key  int NOT NULL COMMENT 'Foreign key linking to the account associated with the fee' CONSTRAINT fk_fee_account REFERENCES finance_analytics.dim_account,
 customer_key int NOT NULL COMMENT 'Foreign key connecting to the customer who incurred the fee' CONSTRAINT fk_fee_customer REFERENCES finance_analytics.dim_customer,
 product_key  int COMMENT 'Optional foreign key to the product associated with the fee' CONSTRAINT fk_fee_product REFERENCES finance_analytics.dim_product,
 currency_key int COMMENT 'Optional foreign key to the currency of the fee' CONSTRAINT fk_fee_currency REFERENCES finance_analytics.dim_currency,
 fee_type     string NOT NULL COMMENT 'Monthly, Overdraft, ATM, Wire, FX',
 fee_amount   decimal(15, 2) NOT NULL COMMENT 'Total amount of the fee assessed',
 waived_flag  boolean NOT NULL COMMENT 'Indicates whether the fee was waived or charged'
)
 COMMENT 'Assessed account fees with waiver tracking';
