-- ********************************** SqlDBM: Databricks *********************************
-- * Generated by SqlDBM: Sample Project:  Finance Analytics by eric.ruiz+yew@sqldbm.com *

-- ************************************** finance_analytics.dim_campaign
CREATE TABLE finance_analytics.dim_campaign
(
 campaign_key int NOT NULL COMMENT 'Unique identifier for each marketing campaign record' CONSTRAINT pk_dim_campaign PRIMARY KEY,
 campaign_id  string NOT NULL COMMENT 'External identifier for the marketing campaign',
 campaign_nm  string NOT NULL COMMENT 'Descriptive name of the marketing campaign',
 channel_key  int COMMENT 'Foreign key referencing the marketing channel used for the campaign',
 start_dt     date COMMENT 'Date when the marketing campaign begins',
 end_dt       date COMMENT 'Date when the marketing campaign concludes'
)
 COMMENT 'Marketing campaigns that may influence account openings and usage';
