-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** PRODUCT_T
CREATE TABLE PRODUCT_T
(
 ADDRESS string NOT NULL
);
