-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.SHIPPINGMETHODDIM_T
CREATE TABLE SUPPLYCHAIN.SHIPPINGMETHODDIM_T
(
 SHIPPINGMETHODKEY     number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''ShippingMethodKey'' column contains data related to ''shippingmethodkey''.',
 METHODNAME            varchar(255) NOT NULL COMMENT 'The ''MethodName'' column contains data related to ''methodname''. This column holds name-related data.',
 CARRIER               varchar(255) COMMENT 'The ''Carrier'' column contains data related to ''carrier''.',
 ESTIMATEDDELIVERYTIME number(38,0) COMMENT 'The ''EstimatedDeliveryTime'' column contains data related to ''estimateddeliverytime''. This column stores information related to dates or times.',
 ADDRESS               string NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( SHIPPINGMETHODKEY )
);
