-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CATEGORYDIM_T
CREATE TABLE SUPPLYCHAIN.CATEGORYDIM_T
(
 CATEGORYKEY  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''CategoryKey'' column contains data related to ''categorykey''.',
 CATEGORYNAME varchar(255) NOT NULL COMMENT 'The ''CategoryName'' column contains data related to ''categoryname''. This column holds name-related data.',
 DESCRIPTION  varchar(500) COMMENT 'The ''Description'' column contains data related to ''description''.',
 LastUpdated  timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( CATEGORYKEY )
);
