-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CUSTOMERFEEDBACKFACT_T
CREATE TABLE SUPPLYCHAIN.CUSTOMERFEEDBACKFACT_T
(
 FEEDBACKID       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''FeedbackID'' column contains data related to ''feedbackid''. This column likely represents an identifier.',
 CUSTOMERKEY      number(38,0) COMMENT 'The ''CustomerKey'' column contains data related to ''customerkey''.',
 PRODUCTKEY       number(38,0) COMMENT 'The ''ProductKey'' column contains data related to ''productkey''.',
 DATEKEY          date COMMENT 'The ''DateKey'' column contains data related to ''datekey''. This column stores information related to dates or times.',
 FEEDBACKRATING   number(38,0) COMMENT 'The ''FeedbackRating'' column contains data related to ''feedbackrating''.',
 FEEDBACKCOMMENTS varchar(500) COMMENT 'The ''FeedbackComments'' column contains data related to ''feedbackcomments''.',
 LastUpdated      timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( FEEDBACKID )
);
