-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ENVIRONMENTALIMPACTFACT_T
CREATE TABLE SUPPLYCHAIN.ENVIRONMENTALIMPACTFACT_T
(
 IMPACTID         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ImpactID'''' column contains data related to ''''impactid''''. This column likely represents an identifier.',
 DATEKEY          date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 EMISSIONSCO_2_KG number(10,2) COMMENT 'The ''''EmissionsCO2Kg'''' column contains data related to ''''emissionsco2kg''''.',
 SHIPMENTID       number(38,0) NOT NULL COMMENT 'The ''''ShipmentID'''' column contains data related to ''''shipmentid''''. This column likely represents an identifier.',

 CONSTRAINT PK_1 PRIMARY KEY ( IMPACTID ),
 CONSTRAINT FK_13 FOREIGN KEY ( SHIPMENTID ) REFERENCES SUPPLYCHAIN.SHIPMENT_T ( SHIPMENTID )
);
