-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.WAREHOUSEZONEDIM_T
CREATE TABLE SUPPLYCHAIN.WAREHOUSEZONEDIM_T
(
 ZONEKEY      number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''ZoneKey'' column contains data related to ''zonekey''.',
 WAREHOUSEKEY number(38,0) COMMENT 'The ''WarehouseKey'' column contains data related to ''warehousekey''.',
 ZONENAME     varchar(100) COMMENT 'The ''ZoneName'' column contains data related to ''zonename''. This column holds name-related data.',
 ZONEFUNCTION varchar(100) COMMENT 'The ''ZoneFunction'' column contains data related to ''zonefunction''.',

 CONSTRAINT PK_1 PRIMARY KEY ( ZONEKEY )
);
