-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.INVENTORY_T
CREATE TABLE SUPPLYCHAIN.INVENTORY_T
(
 INVENTORYID number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''InventoryID'' column contains data related to ''inventoryid''. This column likely represents an identifier.',
 QUANTITY    number(38,0) NOT NULL COMMENT 'The ''Quantity'' column contains data related to ''quantity''.',
 LastUpdated timestamp NOT NULL DEFAULT CURRENT_DATE(),
 PRODUCTID   number(38,0) NOT NULL,
 WAREHOUSEID number(38,0) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( INVENTORYID )
) WITH TAG (SUPPLYCHAIN.DATA_OWNER = 'SUPPLYCHAINTEAM');
