-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.SUPPLIERPAYMENTS_T
CREATE TABLE SUPPLYCHAIN.SUPPLIERPAYMENTS_T
(
 PAYMENTID        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''PaymentID'' column contains data related to ''paymentid''. This column likely represents an identifier.',
 PAYMENTDATE      date NOT NULL COMMENT 'The ''PaymentDate'' column contains data related to ''paymentdate''. This column stores information related to dates or times.',
 AMOUNT           number(15,2) NOT NULL COMMENT 'The ''Amount'' column contains data related to ''amount''. This column represents a numeric value, likely related to amounts or prices.',
 PAYMENTMETHOD    varchar(50) COMMENT 'The ''PaymentMethod'' column contains data related to ''paymentmethod''.',
 PAYMENTREFERENCE varchar(100) COMMENT 'The ''PaymentReference'' column contains data related to ''paymentreference''.',
 S_ID             number(38,0) NOT NULL COMMENT 'The ''SupplierID'' column contains data related to ''supplierid''. This column likely represents an identifier.',
 LastUpdated      timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( PAYMENTID ),
 CONSTRAINT FK_15 FOREIGN KEY ( S_ID ) REFERENCES SUPPLYCHAIN.SUPPLIER_T ( S_ID )
) WITH TAG (SUPPLYCHAIN.ACCESS_LEVEL = 'RESTRICTED');
