-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.PURCHASEORDER_T
CREATE TABLE SUPPLYCHAIN.PURCHASEORDER_T
(
 PURCHASEORDERID number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''PurchaseOrderID'' column contains data related to ''purchaseorderid''. This column likely represents an identifier.',
 ORDERDATE       date NOT NULL COMMENT 'The ''OrderDate'' column contains data related to ''orderdate''. This column stores information related to dates or times.',
 DELIVERYDATE    date COMMENT 'The ''DeliveryDate'' column contains data related to ''deliverydate''. This column stores information related to dates or times.',
 STATUS          varchar(50) NOT NULL COMMENT 'The ''Status'' column contains data related to ''status''. This column contains status information.',
 TOTALAMOUNT     number(15,2) COMMENT 'The ''TotalAmount'' column contains data related to ''totalamount''. This column represents a numeric value, likely related to amounts or prices.',
 S_ID            number(38,0) NOT NULL COMMENT 'The ''SupplierID'' column contains data related to ''supplierid''. This column likely represents an identifier.',
 LastUpdated     timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( PURCHASEORDERID ),
 CONSTRAINT FK_16 FOREIGN KEY ( S_ID ) REFERENCES SUPPLYCHAIN.SUPPLIER_T ( S_ID )
);
