-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.ORDERRETURNSPOLICYDIM_T
CREATE TABLE SUPPLYCHAIN.ORDERRETURNSPOLICYDIM_T
(
 RETURNSPOLICYKEY  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''ReturnsPolicyKey'' column contains data related to ''returnspolicykey''.',
 POLICYDESCRIPTION varchar(255) COMMENT 'The ''PolicyDescription'' column contains data related to ''policydescription''.',
 RETURNWINDOWDAYS  number(38,0) COMMENT 'The ''ReturnWindowDays'' column contains data related to ''returnwindowdays''.',
 ADDRESS           string NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( RETURNSPOLICYKEY )
);
