-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.WAREHOUSEMAINTENANCEFACT_T
CREATE TABLE SUPPLYCHAIN.WAREHOUSEMAINTENANCEFACT_T
(
 MAINTENANCEID            number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''MaintenanceID'' column contains data related to ''maintenanceid''. This column likely represents an identifier.',
 WAREHOUSEKEY             number(38,0) COMMENT 'The ''WarehouseKey'' column contains data related to ''warehousekey''.',
 DATEKEY                  date COMMENT 'The ''DateKey'' column contains data related to ''datekey''. This column stores information related to dates or times.',
 MAINTENANCETYPE          varchar(50) COMMENT 'The ''MaintenanceType'' column contains data related to ''maintenancetype''.',
 MAINTENANCECOST          number(10,2) COMMENT 'The ''MaintenanceCost'' column contains data related to ''maintenancecost''.',
 MAINTENANCEDURATIONHOURS number(5,2) COMMENT 'The ''MaintenanceDurationHours'' column contains data related to ''maintenancedurationhours''.',
 LastUpdated              timestamp NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( MAINTENANCEID )
);
