-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.EMPLOYEEPERFORMANCEFACT_T
CREATE TABLE SUPPLYCHAIN.EMPLOYEEPERFORMANCEFACT_T
(
 PERFORMANCEID    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''PerformanceID'' column contains data related to ''performanceid''. This column likely represents an identifier.',
 E_K              number(38,0) COMMENT 'The ''EmployeeKey'' column contains data related to ''employeekey''.',
 DATEKEY          date COMMENT 'The ''DateKey'' column contains data related to ''datekey''. This column stores information related to dates or times.',
 TASKSCOMPLETED   number(38,0) COMMENT 'The ''TasksCompleted'' column contains data related to ''taskscompleted''.',
 ERRORSMADE       number(38,0) COMMENT 'The ''ErrorsMade'' column contains data related to ''errorsmade''.',
 PERFORMANCESCORE number(5,2) COMMENT 'The ''PerformanceScore'' column contains data related to ''performancescore''.',

 CONSTRAINT PK_1 PRIMARY KEY ( PERFORMANCEID )
);
