-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.TRANSPORTVEHICLEDIM_T
CREATE TABLE SUPPLYCHAIN.TRANSPORTVEHICLEDIM_T
(
 VEHICLEKEY   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''VehicleKey'' column contains data related to ''vehiclekey''.',
 VEHICLEID    varchar(100) COMMENT 'The ''VehicleID'' column contains data related to ''vehicleid''. This column likely represents an identifier.',
 VEHICLETYPE  varchar(100) COMMENT 'The ''VehicleType'' column contains data related to ''vehicletype''.',
 CAPACITY     number(38,0) COMMENT 'The ''Capacity'' column contains data related to ''capacity''.',
 LICENSEPLATE varchar(20) COMMENT 'The ''LicensePlate'' column contains data related to ''licenseplate''.',
 OPERATORNAME varchar(100) COMMENT 'The ''OperatorName'' column contains data related to ''operatorname''. This column holds name-related data.',
 ADDRESS      string NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( VEHICLEKEY )
);
