-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.SUPPLIER_T
CREATE TABLE SUPPLYCHAIN.SUPPLIER_T
(
 SUPPLIERID   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''SupplierID'' column contains data related to ''supplierid''. This column likely represents an identifier.',
 SUPPLIERNAME varchar(255) NOT NULL COMMENT 'The ''SupplierName'' column contains data related to ''suppliername''. This column holds name-related data.',
 CONTACTNAME  varchar(255) COMMENT 'The ''ContactName'' column contains data related to ''contactname''. This column holds name-related data.',
 CONTACTTITLE varchar(255) COMMENT 'The ''ContactTitle'' column contains data related to ''contacttitle''.',
 ADDRESS      string NOT NULL,
 CITY         varchar(100) COMMENT 'The ''City'' column contains data related to ''city''.',
 STATE        varchar(100) COMMENT 'The ''State'' column contains data related to ''state''.',
 ZIPCODE      varchar(20) COMMENT 'The ''ZipCode'' column contains data related to ''zipcode''.',
 COUNTRY      varchar(100) COMMENT 'The ''Country'' column contains data related to ''country''.',
 PHONE        varchar(20) COMMENT 'The ''Phone'' column contains data related to ''phone''.',
 EMAIL        varchar(100) COMMENT 'The ''Email'' column contains data related to ''email''.',
 WEBSITE      varchar(100) COMMENT 'The ''Website'' column contains data related to ''website''.',

 CONSTRAINT PK_1 PRIMARY KEY ( SUPPLIERID )
) WITH TAG (SUPPLYCHAIN.PII = 'YES');
