-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 67 by eric.ruiz+yew@sqldbm.com *

-- ************************************** TABLE_42_T
CREATE TABLE TABLE_42_T
(
 ADDRESS string NOT NULL
);
