-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** TABLE_41_T
CREATE TABLE TABLE_41_T
(
 LastUpdated timestamp NOT NULL
);
