-- ************************** SqlDBM: Snowflake *************************
-- **** Generated by SqlDBM: Snowflake 43 by eric.ruiz+yew@sqldbm.com ***

-- ************************************** table_42
CREATE TABLE table_42
(

);
