-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Snowflake Demo 45 by eric.ruiz+yew@sqldbm.com *

-- ************************************** TABLE_41_T
CREATE TABLE TABLE_41_T
(
 ADDRESS string NOT NULL
);
